version: '3.6'

# 배포 관련 파일입니다. 담당자와 상의 없이 수정 금지
services:
  backend:
    container_name: gg-backend
    image: ghcr.io/gyeongnam-gyeongmae/gyeongnam-gyeongmae-api:develop
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - gg-backend
    depends_on:
      - postgres
      - redis
    platform: linux/amd64
  postgres:
    container_name: gg-postgres
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - gg-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: gg-redis
    image: redis:6.2.6
    ports:
      - 6379:6379
    networks:
      - gg-backend

volumes:
  postgres-data:

networks:
  gg-backend: