version: '3.6'

services:
  backend:
    container_name: gg-backend
    image: ghcr.io/gyeongnam-gyeongmae/gyeongnam-gyeongmae-api:latest
    env_file:
      - .env
    ports:
      - 12000:12000
    networks:
      - gg-backend
  postgres:
    container_name: gg-postgres
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 15432:5432
    networks:
      - gg-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./install-extensions.sql:/docker-entrypoint-initdb.d/initialize.sql

volumes:
  postgres-data:

networks:
  gg-backend:
