server.port: ${PORT}
spring.config.import:
  - application-mailer.yml
  - application-postgresql.yml
# oauth2 vendors
  - oauth/kakao-oauth.yml
cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    region:
        static: ${cloud.aws.region.static}
        auto: ${cloud.aws.region.auto}
    stack:
      auto: false
spring:
  boot:
    admin:
      client:
        url:
          - ${SPRING_BOOT_ADMIN_URL}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB